const js = require('@eslint/js');

module.exports = [
  {
    ignores: [
      'node_modules/',
      'dist/',
      'coverage/',
      'SistersPromiseMobile/',
      'assets/css/',
      'assets/js/core/',
      'assets/js/plugins/',
      'assets/js/material-kit.js',
      'assets/js/material-kit.min.js',
      'assets/scss/',
      'ConnectionsSetupFiles/',
      'build.js',
      'setup-database-mongodb.js',
      'sisters-promise-products-with-images.js',
      'import-products-from-csv.js',
      'seed-blog-posts.js',
      'seed-blog-posts-trending.js',
      'update-product-details.js',
      'regression_test_suite.js',
      'test_all_endpoints*.js',
      'test_rewards_endpoints.js',
      'endpoint_status_check.js',
    ],
  },
  js.configs.recommended,
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        // Node.js globals
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        URL: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-undef': 'error',
      'no-constant-condition': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-prototype-builtins': 'off',
      'no-useless-escape': 'warn',
    },
  },
  {
    files: ['assets/js/**/*.js'],
    languageOptions: {
      sourceType: 'script',
      globals: {
        // Browser globals
        window: 'writable',
        document: 'readonly',
        navigator: 'readonly',
        fetch: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        location: 'readonly',
        history: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        HTMLElement: 'readonly',
        Event: 'readonly',
        FormData: 'readonly',
        URLSearchParams: 'readonly',
        Headers: 'readonly',
        AbortController: 'readonly',
        DOMParser: 'readonly',
        // Libraries loaded via CDN
        bootstrap: 'readonly',
        grecaptcha: 'readonly',
        gtag: 'readonly',
        // App modules loaded via separate script tags
        AuthService: 'writable',
        SquareIntegration: 'writable',
        BlogModule: 'writable',
      },
    },
    rules: {
      'no-redeclare': 'off',
    },
  },
  {
    files: ['tests/**/*.js', '**/*.test.js', '**/*.spec.js'],
    languageOptions: {
      globals: {
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        jest: 'readonly',
      },
    },
  },
];
